Revert "Fix Issue 21299: Undefined reference to dmd.root.stringtable.StringValue!(Type).lstring()"
This reverts commit 46a3a126e76fc727d08c1ccbb3945585abc69dad.