Windows: Fix build regressions with pure MSVC toolchain
While updating & verifying the build-LDC Wiki pages, I've noticed that
the recent Objective-C improvements broke the build with VS 2022,
complaining about a few:

error C7555: use of designated initializers requires at least '/std:c++20'