etc.linux.memoryerror: Adapt to dynamic SIGSTKSZ since glibc v2.34 (dlang/dmd!22473)
This fixes segfault-handler tests for LDC Linux CI, apparently caused
by an insufficient alternate-stack size. Claude was able to diagnose
the problem: https://github.com/ldc-developers/ldc/pull/5041#issuecomment-3689617009