Delete -L--no-warn-search-mismatch on multilib builds
% ldc -linker=lld a.d
ld.lld: error: unknown argument '--no-warn-search-mismatch'
...

lld does not implement this option (https://bugs.llvm.org/show_bug.cgi?id=43740).
I think the option not useful because:

1) This usually indicates real library path configuration problems that should not be ignored.
2) If a .so is actually a linker script that includes other libraries,
 but without an OUTPUT_FORMAT directive, GNU ld and gold's behavior of
 skipping incompatible libraries may still not work if the linker script
 contents are different.
 For example, libncurses.so on Debian does not include an OUTPUT_FORMAT directive.

In addition, clang never passes this option.