fix dlang/dmd!21476: Presence of move constructor causes overload error (dlang/dmd!21477)
Move constructors were incorrectly being considered as regular
constructors, which resulted in the test case failing with:
```
compilable/test21476.d(12): Error: none of the overloads of `this` are callable using argument types `(string)`
    auto o = S21476("aoe");
                   ^
compilable/test21476.d(6):        Candidates are: `test21476.S21476.this(ref return scope S21476)`
    this(ref return scope S21476);
    ^
compilable/test21476.d(7):                        `test21476.S21476.this(return scope S21476)`
    this(return scope S21476);
    ^
```
With this change, a struct literal is now used to construct the object.