Some of the c-library math function have the pure attribute set. Update needed for DragonFly.
Caused trouble compiling phobos since https://github.com/dlang/phobos/pull/6409

Phobos Compile Error:
std/math.d(4598): Error: `pure` function `std.math.nearbyint` cannot call impure function `core.stdc.math.nearbyintl`